services:
  vidlvery:
    build: .
    environment:
      WATCH_DIRECTORY_PATH: /tmp/vidlvery
      PUBLIC_DIRECTORY_PATH: /tmp/vidlvery
      VIDEOS_BASE_URL: "${VIDEOS_BASE_URL}"
      SMTP_FROM: "${SMTP_FROM}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASS: "${SMTP_PASS}"
    ports:
      - 3000:3000
    volumes:
      - watch-directory:/tmp/vidlvery
    restart: unless-stopped

  ffmpeg-queue:
    build:
      context: .
      dockerfile: ffmpeg-queue.Dockerfile
    volumes:
      - watch-directory:/tmp/vidlvery
    restart: unless-stopped

volumes:
  watch-directory:
