export const ENV_WATCH_DIRECTORY_PATH_KEY = 'WATCH_DIRECTORY_PATH';
export const ENV_PUBLIC_DIRECTORY_PATH_KEY = 'PUBLIC_DIRECTORY_PATH';
export const CONFIG_VIDEOS_BASE_URL_KEY = 'VIDEOS_BASE_URL';
export const CONFIG_SMTP_FROM_KEY = 'SMTP_FROM';
export const CONFIG_SMTP_HOST_KEY = 'SMTP_HOST';
export const CONFIG_SMTP_PORT_KEY = 'SMTP_PORT';
export const CONFIG_SMTP_USER_KEY = 'SMTP_USER';
export const CONFIG_SMTP_PASS_KEY = 'SMTP_PASS';
