name: Build and Push Docker image to registry

on:
  push:
    tags: ["v*"]

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}
      -
        name: Docker Vidlvery meta
        id: vidlvery-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      -
        name: Build and push Vidlvery docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.vidlvery-meta.outputs.tags }}
          labels: ${{ steps.vidlvery-meta.outputs.labels }}

      -
        name: Docker Vidlvery meta
        id: ffmpeg-queue-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ffmpeg-queue
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      -
        name: Build and push ffmpeg side-car docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ffmpeg-queue.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.ffmpeg-queue-meta.outputs.tags }}
          labels: ${{ steps.ffmpeg-queue-meta.outputs.labels }}
